name: Keep Alive

on:
  schedule:
    - cron: '*/4 * * * *'  # Executa a cada 5 minutos

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ou a versão de Node.js desejada

      - name: Install dependencies
        run: npm install

      - name: Run keep-alive script
        run: npm start
