name: Enviar Requisição GET

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  send-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Enviar requisição GET
        run: |
          curl -X GET https://backendccraft.onrender.com/api/mail/send
